config/routes.rb
Rails.application.routes.draw do
  get "home/index"

  resource :session, only: %i[new create destroy]
  resources :users
  resources :password_resets

  get "signup", to: "users#new"
  delete "logout", to: "sessions#destroy", as: :logout
  get    "login",  to: "sessions#new"
  get "/users/login_status", to: "users#login_status"


  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  #


  resources :domain_crawlers do
    collection do
      get  :set_header, :display_group, :delete_result
      post :search, :add_result, :remove_group_result
      get  :group_action, :expand_contract_action, :domain_action,
         :more_results, :process_more_results, :previous_search, :tidy_up
    end
  end

  root "users#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password(validations: false)
  has_many :domain_crawlers

  validates_uniqueness_of :email, unless: :guest?
  validates_presence_of :password, :on => :create, unless: :guest?

  before_create { generate_token(:auth_token) }
  def self.new_guest
    logger.info "*** calling self.new_guest"
    new_guest_user = User.new
    new_guest_user.guest = true
    new_guest_user.save!


    return new_guest_user

  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    
    begin
      GraphUserMailer.password_reset(self)
      true
    rescue EmailDeliveryError => e
      Rails.logger.error "Failed to send password reset email: #{e.message}"
      false
    end
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/users_controller.rb

require "net/http"
require "json"

class UsersController < ApplicationController
  def new
    logger.info "UsersController new called"
    @user = User.new
  end
  def login_status
    render partial: "users/login_status"
  end





  def create
    logger.info "UsersController create called"
    logger.info "params keys: #{params.keys.inspect}"
    logger.info "g-recaptcha-response: #{params["g-recaptcha-response"]}"
    index
=begin
    logger.info "User params inspect #{user_params.inspect}"
    res = Net::HTTP.post_form(URI("https://www.google.com/recaptcha/api/siteverify"),
    secret: ENV["RECAPTCHA_SECRET_KEY"],
    response: params["g-recaptcha-response"],
    remoteip: request.remote_ip
)
result = JSON.parse(res.body)
Rails.logger.debug "Manual verification: #{result.inspect}"
=end
    @user = User.new(user_params)
    user_save = @user.save
    verify_captcha_value = verify_recaptcha(model: @user)
    unless verify_captcha_value
      Rails.logger.warn("Recaptcha verification failed: #{@user.errors[:recaptcha].inspect}")
    end
    logger.info "User save: #{user_save}, verify_captcha_value: #{verify_captcha_value}"

    if user_save and verify_captcha_value
      cookies[:auth_token] = @user.auth_token
      logger.info "catpcha verified"
      guest_user = current_user
      guest_user.destroy
      session[:user_id] =@user.id


      redirect_to domain_crawlers_url, notice: "Account successfully created! Welcome to St. Thomas the Search Engine."
    else
      if !verify_captcha_value
        @user.errors.add(:base, "CAPTCHA verification failed. Please try again.")
        logger.info "catpcha unverified"
      end
      if !user_save
        @user.errors.add(:base, "Unable to create user save: #{user_save} - either user already exists or the data is invalid")
        logger.info "user unverified"
      end

      render "new"
    end
  end

  def index
    logger.info "UsersController index called"
    @users = User.all
    @just_logged_out = session.delete(:just_logged_out)
  end

  def update
    if @user.update_attributes(params[:user])
      sign_in @user
      flash[:success] = "Profile updated"
      redirect_to new_domain_crawler_path
    else
      render "edit"
    end
  end

  private

  def user_params
    logger.info "UsersController user_params called"
    params.require(:user).permit(:email, :first_name, :second_name, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_login_status.html.erb
  <div class="login-status-div" id="login-status-div-id">
  <% if !current_user or current_user.guest %>
  <%= link_to "Sign Up", signup_path  %> or
      <%= link_to "Log In", login_path %>

  <% else %>
      Logged in as <%= current_user.email %>. <br>
      <%= link_to "Log Out", logout_path, method: :delete %>
  <% end %>
  </div>

app/views/users/_user_header.html.erb
<script nonce="<%= content_security_policy_nonce %>">
  //console.log("s");
</script>
<div class="user-header">
  <div class="dominican-logo"></div>
  <div class="thomas-header"> St. Thomas <br> The Search Engine </div>
  <%= render 'users/login_status', current_user: current_user %>

</div>

app/views/users/index.html.erb
<script nonce="<%= content_security_policy_nonce %>">
  document.dispatchEvent(new Event("index:user_loaded"));
  window.dispatchEvent(new Event("refresh:loginStatus"));
  document.dispatchEvent(new Event("latininitializers"));

  <% if @just_logged_out %>
  console.log("User just logged out, dispatching domain_summary:guest_loaded event");
  document.dispatchEvent(new Event("domain_summary:guest_loaded"));
  <% end %>

  //console.log("t");
</script>

app/views/users/new.html.erb
<script nonce="<%= content_security_policy_nonce %>">
  //console.log("u");  
</script>
<h1>Sign Up</h1>

<%= form_for @user, html: { data: { turbo: false } }  do |f| %>
    <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <script nonce="<%= content_security_policy_nonce %>">
              document.dispatchEvent(new Event("hideforms")); 
        </script>
    <% end %>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :first_name%><br />
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :second_name%><br />
      <%= f.text_field :second_name %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>

    <%= recaptcha_tags %>
   


    <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

<script nonce="<%= content_security_policy_nonce %>">
document.dispatchEvent(new Event("hideforms")); 
document.querySelectorAll('textarea[name="g-recaptcha-response"]').forEach((el) => {
      if (!el.id) {
        el.remove()
        return;
      }
    });
</script>